parameters:
  core_application:
    urls:
      base: http://ci.app.simplytestable.com
      test_start: /tests/{canonical-url}/start/
      test_status: /tests/{canonical-url}/{test_id}/status/
      test_cancel: /tests/{canonical-url}/{test_id}/cancel/
      test_list_urls: /tests/{canonical-url}/{test_id}/urls/
      task_status: /tasks/{canonical-url}/{test_id}/{task_id}/status/
  content_type_web_resource_map:
    default: webignition\WebResource\WebResource
    application/json: webignition\WebResource\JsonDocument\JsonDocument
  task-output-result-parsers:
    "HTML validation":
        class: SimplyTestable\WebClientBundle\Services\TaskOutput\ResultParser\HtmlValidationResultParser