homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SimplyTestableWebClientBundle:Default:index }

app:
    pattern:  /app/
    defaults: { _controller: SimplyTestableWebClientBundle:App:index }

test_start:
    pattern:  /test/start/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:start }