services:
  simplytestable.services.httpClient:
    class:  webignition\Http\Client\Client
    
  simplytestable.services.webresourceservice:
    class:   SimplyTestable\WebClientBundle\Services\WebResourceService
    arguments:
        httpClient: "@simplytestable.services.httpClient"
        contentTypeWebResourceMap: %content_type_web_resource_map%    


  simplytestable.services.testservice:
    class:   SimplyTestable\WebClientBundle\Services\TestService  
    arguments:
        entityManager: "@doctrine.orm.entity_manager"  
        parameters: %core_application%
        webResourceService: "@simplytestable.services.webresourceservice"            

  simplytestable.services.taskoutputservice:
    class:   SimplyTestable\WebClientBundle\Services\TaskOutputService  
    arguments:
        entityManager: "@doctrine.orm.entity_manager"      
        parameters: %core_application%
        webResourceService: "@simplytestable.services.webresourceservice"
        
  simplytestable.services.taskoutputdeserializerfactoryservice:
    class:   SimplyTestable\WebClientBundle\Services\TaskOutputDeserializer\FactoryService
    arguments:
        deserlializers: %task-output-deserializers%    