services:
  simplytestable.services.httpClient:
    class:  webignition\Http\Client\Client
    
  simplytestable.services.webresourceservice:
    class:   SimplyTestable\WebClientBundle\Services\WebResourceService
    arguments:
        httpClient: "@simplytestable.services.httpClient"
        contentTypeWebResourceMap: %content_type_web_resource_map%
        
  simplytestable.services.coreapplicationservice:
    class:   SimplyTestable\WebClientBundle\Services\CoreApplicationService
    arguments:
        webResourceService: "@simplytestable.services.webresourceservice"